services:
  reverse-proxy:
    image: traefik:v3.1
    command: 
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      # Porta HTTP
      - "80:80"
      # Web UI
      - "8080:8080"
    volumes:
      # Para o Traefik acessar o Docker
      - "/var/run/docker.sock:/var/run/docker.sock"
  web:
    container_name: app
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres
    container_name: database
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  data:
