# Usar a imagem oficial do PostgreSQL como base
FROM postgres:latest

# Instalar curl e outras dependências necessárias
RUN apt-get update && \
    apt-get install -y curl unzip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Baixar e instalar o rclone manualmente
RUN curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip && \
    unzip rclone-current-linux-amd64.zip && \
    cd rclone-*-linux-amd64 && \
    cp rclone /usr/bin/ && \
    chown root:root /usr/bin/rclone && \
    chmod 755 /usr/bin/rclone && \
    rm -rf rclone-current-linux-amd64.zip rclone-*-linux-amd64

# Criar o diretório de configuração para o rclone e copiar o arquivo de configuração
RUN mkdir -p /root/.config/rclone
COPY rclone.conf /root/.config/rclone/rclone.conf
